"""Add image description fields to Exercice

Revision ID: 3910e5ed12a5
Revises: e8768292ac95
Create Date: 2025-11-25 18:05:50.812853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3910e5ed12a5'
down_revision = 'e8768292ac95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_description_fr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_keywords', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_elements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.drop_column('image_elements')
        batch_op.drop_column('image_keywords')
        batch_op.drop_column('image_description_en')
        batch_op.drop_column('image_description_fr')

    # ### end Alembic commands ###
