"""Add date_mise_a_jour column to users table

Revision ID: 5afa11eb490a
Revises: 3910e5ed12a5
Create Date: 2026-01-25 13:04:03.352773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5afa11eb490a'
down_revision = '3910e5ed12a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('eleve_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type_abonnement',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('montant_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='montant_total::float')
        batch_op.alter_column('montant_commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='montant_commission::float')
        batch_op.alter_column('taux_base',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='taux_base::float')
        batch_op.alter_column('details_bonus',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='details_bonus::json')
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('statut_eleve',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('date_paiement_eleve',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('date_calcul',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('date_approbation',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('date_versement_manuel',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('preuve_versement',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_commissions_eleve'))
        batch_op.drop_index(batch_op.f('idx_commissions_enseignant'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('info_versement_enseignant', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('frequence_versement',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('seuil_minimum',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='seuil_minimum::float')
        batch_op.drop_index(batch_op.f('idx_info_versement_enseignant'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True))
        batch_op.alter_column('disponibilites',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('versements_manuels', schema=None) as batch_op:
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('montant_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='montant_total::float')
        batch_op.alter_column('frais_transaction',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='frais_transaction::float')
        batch_op.alter_column('montant_net',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='montant_net::float')
        batch_op.alter_column('email_interac',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date_demande',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('date_versement',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('preuve_versement',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_versements_manuels_enseignant'))
        batch_op.drop_index(batch_op.f('idx_versements_manuels_statut'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versements_manuels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_versements_manuels_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('idx_versements_manuels_enseignant'), ['enseignant_id'], unique=False)
        batch_op.alter_column('preuve_versement',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('date_versement',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('date_demande',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('email_interac',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('montant_net',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('frais_transaction',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('montant_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('disponibilites',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_column('date_mise_a_jour')

    with op.batch_alter_table('info_versement_enseignant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_info_versement_enseignant'), ['enseignant_id'], unique=False)
        batch_op.alter_column('seuil_minimum',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('frequence_versement',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_commissions_enseignant'), ['enseignant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_commissions_eleve'), ['eleve_id'], unique=False)
        batch_op.alter_column('preuve_versement',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_versement_manuel',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('date_approbation',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('date_calcul',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('date_paiement_eleve',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('statut_eleve',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('details_bonus',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('taux_base',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('montant_commission',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('montant_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('type_abonnement',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('eleve_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('enseignant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###