"""Ajout champs diagnostic bayesien student responses

Revision ID: d63441fb4d3c
Revises: 5afa11eb490a
Create Date: 2026-06-09 14:05:46.105645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63441fb4d3c'
down_revision = '5afa11eb490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_erreur', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('niveau_difficulte', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('temps_passe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aide_utilisee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feedback_ia_structure', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_responses', schema=None) as batch_op:
        batch_op.drop_column('feedback_ia_structure')
        batch_op.drop_column('aide_utilisee')
        batch_op.drop_column('temps_passe')
        batch_op.drop_column('niveau_difficulte')
        batch_op.drop_column('type_erreur')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
