"""ajout_champs_essai_gratuit

Revision ID: e8768292ac95
Revises: f87999888573
Create Date: 2025-10-21 13:55:10.029882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8768292ac95'
down_revision = 'f87999888573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_fin_essai', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('statut_essai', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('statut_essai')
        batch_op.drop_column('date_fin_essai')

    # ### end Alembic commands ###
