"""Ajout champs étendus User

Revision ID: f87999888573
Revises: 
Create Date: 2025-10-20 18:33:39.009524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87999888573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('statut_paiement', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('inscrit_par_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_postal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pays', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_inscription', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_dernier_paiement', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_fin_abonnement', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_verifie', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telephone_verifie', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accepte_cgu', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_acceptation_cgu', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('derniere_connexion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('nombre_connexions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferences_notifications', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences_notifications')
        batch_op.drop_column('timezone')
        batch_op.drop_column('nombre_connexions')
        batch_op.drop_column('derniere_connexion')
        batch_op.drop_column('date_acceptation_cgu')
        batch_op.drop_column('accepte_cgu')
        batch_op.drop_column('telephone_verifie')
        batch_op.drop_column('email_verifie')
        batch_op.drop_column('date_fin_abonnement')
        batch_op.drop_column('date_dernier_paiement')
        batch_op.drop_column('date_inscription')
        batch_op.drop_column('date_naissance')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_payment_intent')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('pays')
        batch_op.drop_column('code_postal')
        batch_op.drop_column('province')
        batch_op.drop_column('ville')
        batch_op.drop_column('adresse')
        batch_op.drop_column('telephone')
        batch_op.drop_column('inscrit_par_admin')
        batch_op.drop_column('statut_paiement')
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
